<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sys_arch" nsURI="http://dlut.ai.fyp/1.0" nsPrefix="sys_arch">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schematics" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safety_related" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure_modes" upperBound="-1"
        eType="#//Failure_Mode_Entry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safety_mechanisms" upperBound="-1"
        eType="#//Safety_Mechanism" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure_Mode_Entry" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failure_mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode_distribution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Safety_Mechanism" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handle" eType="#//Failure_Mode_Entry"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transmission_Wire" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCLComponent" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Resistor" eSuperTypes="#//RCLComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capacitor" eSuperTypes="#//RCLComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacitance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inductor" eSuperTypes="#//RCLComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inductance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerSupply" abstract="true" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ACPowerSupply" eSuperTypes="#//PowerSupply">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freuqnecy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DCPowerSupply" eSuperTypes="#//PowerSupply"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lamp" eSuperTypes="#//Resistor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input_voltage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input_current" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MCU" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transistor" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="MOSFET" eSuperTypes="#//Transistor"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPAmp" eSuperTypes="#//Transistor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ground" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Diode" eSuperTypes="#//Transistor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Triode" eSuperTypes="#//Transistor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="#//Component"/>
</ecore:EPackage>
